# Generated by Django 5.2.3 on 2026-07-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',), 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модульдер'},
        ),
        migrations.AlterModelOptions(
            name='lessondocs',
            options={'verbose_name': 'Модуль құжаты', 'verbose_name_plural': 'Модуль құжаттары'},
        ),
        migrations.AlterModelOptions(
            name='userlesson',
            options={'verbose_name': 'Қолданушының модулі', 'verbose_name_plural': 'Қолданушының модульдері'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.userlesson', verbose_name='Қолданушының модулі'),
        ),
        migrations.AlterField(
            model_name='lessondocs',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='core.lesson', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.lesson', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='status',
            field=models.CharField(choices=[('no-started', 'Модуль басталмады'), ('in-progress', 'Модуль өтілуде'), ('finished', 'Модуль аяқталды')], default='no-started', max_length=64, verbose_name='Статус'),
        ),
    ]
