# Generated by Django 5.2.3 on 2026-07-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lesson_options_alter_lessondocs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('order',), 'verbose_name': 'Тарау', 'verbose_name_plural': 'Тараулар'},
        ),
        migrations.AlterModelOptions(
            name='userchapter',
            options={'verbose_name': 'Қолданушының тарауы', 'verbose_name_plural': 'Қолданушының тараулары'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.chapter', verbose_name='Тарау'),
        ),
        migrations.AlterField(
            model_name='userchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.chapter', verbose_name='Тарау'),
        ),
    ]
