# Generated by Django 5.2.3 on 2026-07-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_chapter_options_alter_userchapter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersimulator',
            name='simulator',
        ),
        migrations.RemoveField(
            model_name='usersimulator',
            name='user_task',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('video', 'Видеосабақ'), ('test', 'Тестілеу'), ('matching', 'Сәйкестендіру')], default='theory', max_length=32, verbose_name='Тапсырма түрі'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField(verbose_name='Сол жақ мәтін')),
                ('right_text', models.TextField(verbose_name='Оң жақ мәтін')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Сәйкестендіру жұбы',
                'verbose_name_plural': 'Сәйкестендіру жұптары',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserMatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_right', models.TextField(blank=True, default='', verbose_name='Таңдалған оң жақ мәтін')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matching_answers', to='core.matchingpair', verbose_name='Сәйкестендіру жұбы')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matching_answers', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
            ],
            options={
                'verbose_name': 'Сәйкестендіру жауабы',
                'verbose_name_plural': 'Сәйкестендіру жауаптары',
            },
        ),
        migrations.DeleteModel(
            name='Simulator',
        ),
        migrations.DeleteModel(
            name='UserSimulator',
        ),
    ]
